### ISSUE TITLE
Fix bindata

### ISSUE THREAD

**Issue by hexfusion** [hexfusion/cluster-etcd-operator#20]
https://github.com/jteeuwen/go-bindata this repo should use go-bindata but for now I manually hacked https://github.com/hexfusion/cluster-etcd-operator/blob/render/pkg/operator/v420_00_assets/bindata.go

This is also referenced in the Makefile but doesn't seem to work. We need to fix it and document.

**Comment by jeckersb** [comment]
This seems to work for me?  Deleting the file and then re-generating with make puts it back exactly as it was.

```
[jeckersb@scandi cluster-etcd-operator]$ git status
On branch render
Your branch is up to date with 'hexfusion/render'.

nothing to commit, working tree clean
[jeckersb@scandi cluster-etcd-operator]$ rm pkg/operator/v420_00_assets/bindata.go
[jeckersb@scandi cluster-etcd-operator]$ git status
On branch render
Your branch is up to date with 'hexfusion/render'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        deleted:    pkg/operator/v420_00_assets/bindata.go

no changes added to commit (use "git add" and/or "git commit -a")
[jeckersb@scandi cluster-etcd-operator]$ make update-bindata
ln -s /home/jeckersb/go/src/github.com/openshift/cluster-etcd-operator/vendor "/tmp/tmp.VI1c2rQJNQ/src"
export GOPATH=/tmp/tmp.VI1c2rQJNQ && go install "./vendor/github.com/jteeuwen/go-bindata/..."
/tmp/tmp.VI1c2rQJNQ/bin/go-bindata -nocompress -nometadata -prefix "bindata" -pkg "v420_00_assets" -o "pkg/operator/v420_00_assets/bindata.go" -ignore "OWNERS" ./bindata/v4.2.0/... && gofmt -s -w "pkg/operator/v420_00_assets/bindata.go"
[jeckersb@scandi cluster-etcd-operator]$ git status
On branch render
Your branch is up to date with 'hexfusion/render'.

nothing to commit, working tree clean
[jeckersb@scandi cluster-etcd-operator]$ 
```

**Comment by jeckersb** [comment]
Side note, looks like https://github.com/jteeuwen/go-bindata is abondoned.  Looks like MCO may switch to go-bindata/go-bindata:

https://github.com/openshift/release/pull/3432

Something to keep an eye on.  I guess that would eventually make its way into library-go and be transparent as far as we're concerned.

**Comment by hexfusion** [comment]
confirmed thanks John

**Comment by hexfusion** [comment]
I think we should document usage in Makefile the way it is setup now obfuscates functionality.

**Comment by jeckersb** [comment]
> I think we should document usage in Makefile the way it is setup now obfuscates functionality.

Agreed, the macros hide the make target names so it's not at all obvious.  The only reason I was able to figure out to use "update-bindata" is due to bash completion showing me the list of possible targets.

**Comment by jeckersb** [comment]
Actually the usage is already documented in the Makefile:

```
# It will generate targets {update,verify}-bindata-$(1) logically grouping them in unsuffixed versions of these targets
# and also hooked into {update,verify}-generated for broader integration.
```

Which accurately describes that it creates the targets:
update-bindata-$VERSION
verify-bindata-$VERSION
update-bindata
verify-bindata
update-generated
verify-generated

So I think we can close this.  Re-open if you think it needs additional documentation beyond this.
