### ISSUE TITLE
Dont export Images fields

### ISSUE THREAD

**Issue by hexfusion** [hexfusion/cluster-etcd-operator#27]
https://github.com/hexfusion/cluster-etcd-operator/blob/b440489644e573dc40fd3cad4b3e1e1dd28456c3/pkg/cmd/render/options/config.go#L39-L43

https://github.com/hexfusion/cluster-etcd-operator/blob/b440489644e573dc40fd3cad4b3e1e1dd28456c3/pkg/cmd/render/render.go#L151-L153

no reason for these to be exported we should resolve before feature merge.

**Comment by jeckersb** [comment]
Punting for now.  The struct declaration is under the options package, so in order to reference the fields in render it needs to be exported.  Longer-term we could consider mimicking the way MCO handles this (Images is a map[string]string and uses constants for the keys).

**Comment by hexfusion** [comment]
Yeah this was my bad
